import Link from 'next/link';
import '../styles/globals.css';

export const metadata = {
  title: 'Simple Board',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head />
      <body>
        <div className='main_area'>
          <div className='left_area'>
            <Link href={'/'}>
              <span className='left_area_title'>Simple Board</span>
            </Link>
            <Link href={'/posts/create'}>
              <button className='create_btn'></button>
            </Link>
          </div>
          <div className='right_area'>
            {children}
            <div className='right_footer'>
              App is generated by &nbsp;<span className='right_footer_text'>Next.js</span>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
